In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason 1  Reason 2  Reason 3  Reason 4  Day of the week  Month Value  \
0         0         0         0         1                1            7   
1         0         0         0         0                1            7   
2         0         0         0         0                2            7   
3         1         0         0         0                3            7   
4         0         0         0         0                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

### Using logistic regression which is Classification

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

###### <=3 Moderately absent >4 Excesivly absent

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(), 1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['Excessive Absenteeism'] = targets

In [7]:
data_preprocessed.head()

Reason 1  Reason 2  Reason 3  Reason 4  Day of the week  Month Value  \
0         0         0         0         1                1            7   
1         0         0         0         0                1            7   
2         0         0         0         0                2            7   
3         1         0         0         0                3            7   
4         0         0         0         0                3            7   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [8]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [9]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the week', 'Daily Work Load Average','Distance to Work'], axis=1)

In [10]:
data_with_targets.head()

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         0            7   
3         1         0         0         0            7   
4         0         0         0         0            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [11]:
data_with_targets.shape

(700, 12)

In [12]:
data_with_targets.iloc[:, :14]

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         0            7   
3           1         0         0         0            7   
4           0         0         0         0            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         0            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [13]:
data_with_targets.iloc[:, :-1]

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         0            7   
3           1         0         0         0            7   
4           0         0         0         0            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         0            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

#### Standardising the data

In [15]:
#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

In [16]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self, columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.iloc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [18]:
#columns_to_scale = [ 'Day of the week','Month Value', 'Transportation Expense', 'Distance to Work', 'Age',
 #      'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']

In [19]:
columns_to_omit = ['Reason_1','Reason_2','Reason_3','Reason_4','Education']

In [20]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [21]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [22]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4',
                      'Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [23]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [24]:
scaled_inputs.shape

(700, 11)

In [25]:
scaled_inputs

Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
0   -0.577350  -0.07581 -0.343818  1.388838     0.182726   
1   -0.577350  -0.07581 -0.343818 -0.720027     0.182726   
2   -0.577350  -0.07581 -0.343818 -0.720027     0.182726   
3    1.732051  -0.07581 -0.343818 -0.720027     0.182726   
4   -0.577350  -0.07581 -0.343818 -0.720027     0.182726   
..        ...       ...       ...       ...          ...   
695  1.732051  -0.07581 -0.343818 -0.720027    -0.388293   
696  1.732051  -0.07581 -0.343818 -0.720027    -0.388293   
697  1.732051  -0.07581 -0.343818 -0.720027    -0.388293   
698 -0.577350  -0.07581 -0.343818 -0.720027    -0.388293   
699 -0.577350  -0.07581 -0.343818  1.388838    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

#### Spliting the data into train and testing

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
train_test_split(scaled_inputs, targets)

[     Reason 1  Reason 2  Reason 3  Reason 4  Month Value  \
 30  -0.577350  -0.07581 -0.343818 -0.720027     0.468236   
 514 -0.577350  -0.07581 -0.343818 -0.720027     1.039256   
 429 -0.577350  -0.07581 -0.343818  1.388838    -0.388293   
 3    1.732051  -0.07581 -0.343818 -0.720027     0.182726   
 618 -0.577350  -0.07581 -0.343818  1.388838    -0.959313   
 ..        ...       ...       ...       ...          ...   
 406 -0.577350  -0.07581 -0.343818 -0.720027    -0.959313   
 412 -0.577350  -0.07581 -0.343818  1.388838    -0.673803   
 124 -0.577350  -0.07581 -0.343818  1.388838    -1.530333   
 139  1.732051  -0.07581 -0.343818 -0.720027    -1.244823   
 586 -0.577350  -0.07581 -0.343818 -0.720027    -1.244823   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 30                -0.654143  0.248310         1.002633          0 -0.919030   
 514                1.036026  0.562059        -0.408580          0 -0.019280   
 429               -0.6541

In [28]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state = 20)

In [29]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [30]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic Regression with Sklearn

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
from sklearn import metrics

#### Training the model

In [33]:
reg = LogisticRegression()

In [34]:
reg.fit(x_train, y_train)

LogisticRegression()

In [35]:
reg.score(x_train,y_train)

0.7803571428571429

### Checking the accuracy of the model

In [36]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [37]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [38]:
model_outputs == y_train

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [39]:
np.sum(model_outputs == y_train)

437

In [40]:
np.sum(model_outputs == y_train)/model_outputs.shape[0]

0.7803571428571429

#### Finding the intercepts

In [41]:
reg.intercept_

array([-0.1303345])

In [42]:
reg.coef_

array([[ 1.05442205,  0.04520686,  1.03116475,  0.19495368,  0.2416558 ,
         0.49274043, -0.11907395,  0.24198287, -0.16493693,  0.32888765,
        -0.32878788]])

In [43]:
unscaled_inputs.columns.values

array(['Reason 1', 'Reason 2', 'Reason 3', 'Reason 4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [44]:
feature_name = unscaled_inputs.columns.values

In [45]:
summary_table = pd.DataFrame(columns=['Feature Name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature Name  Coefficient
0                 Reason 1     1.054422
1                 Reason 2     0.045207
2                 Reason 3     1.031165
3                 Reason 4     0.194954
4              Month Value     0.241656
5   Transportation Expense     0.492740
6                      Age    -0.119074
7          Body Mass Index     0.241983
8                Education    -0.164937
9                 Children     0.328888
10                    Pets    -0.328788

## Entering the intercept on top of the table
We shift the intedx of the whole table to leave index 0 empty

In [46]:
summary_table.index = summary_table.index +1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

Feature Name  Coefficient
1                 Reason 1     1.054422
2                 Reason 2     0.045207
3                 Reason 3     1.031165
4                 Reason 4     0.194954
5              Month Value     0.241656
6   Transportation Expense     0.492740
7                      Age    -0.119074
8          Body Mass Index     0.241983
9                Education    -0.164937
10                Children     0.328888
11                    Pets    -0.328788
0                Intercept    -0.130334

In [47]:
summary_table.sort_index()

Feature Name  Coefficient
0                Intercept    -0.130334
1                 Reason 1     1.054422
2                 Reason 2     0.045207
3                 Reason 3     1.031165
4                 Reason 4     0.194954
5              Month Value     0.241656
6   Transportation Expense     0.492740
7                      Age    -0.119074
8          Body Mass Index     0.241983
9                Education    -0.164937
10                Children     0.328888
11                    Pets    -0.328788

#### Interpreting the outputs

In [48]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [49]:
summary_table

Feature Name  Coefficient  Odds_ratio
1                 Reason 1     1.054422    2.870316
2                 Reason 2     0.045207    1.046244
3                 Reason 3     1.031165    2.804330
4                 Reason 4     0.194954    1.215255
5              Month Value     0.241656    1.273356
6   Transportation Expense     0.492740    1.636796
7                      Age    -0.119074    0.887742
8          Body Mass Index     0.241983    1.273772
9                Education    -0.164937    0.847947
10                Children     0.328888    1.389422
11                    Pets    -0.328788    0.719796
0                Intercept    -0.130334    0.877802

In [50]:
summary_table.sort_values('Odds_ratio')

Feature Name  Coefficient  Odds_ratio
11                    Pets    -0.328788    0.719796
9                Education    -0.164937    0.847947
0                Intercept    -0.130334    0.877802
7                      Age    -0.119074    0.887742
2                 Reason 2     0.045207    1.046244
4                 Reason 4     0.194954    1.215255
5              Month Value     0.241656    1.273356
8          Body Mass Index     0.241983    1.273772
10                Children     0.328888    1.389422
6   Transportation Expense     0.492740    1.636796
3                 Reason 3     1.031165    2.804330
1                 Reason 1     1.054422    2.870316

In [51]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature Name  Coefficient  Odds_ratio
1                 Reason 1     1.054422    2.870316
3                 Reason 3     1.031165    2.804330
6   Transportation Expense     0.492740    1.636796
10                Children     0.328888    1.389422
8          Body Mass Index     0.241983    1.273772
5              Month Value     0.241656    1.273356
4                 Reason 4     0.194954    1.215255
2                 Reason 2     0.045207    1.046244
7                      Age    -0.119074    0.887742
0                Intercept    -0.130334    0.877802
9                Education    -0.164937    0.847947
11                    Pets    -0.328788    0.719796

### Testing the model`

In [52]:
reg.score(x_test, y_test)

0.7428571428571429

In [53]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.67344623, 0.32655377],
       [0.59726439, 0.40273561],
       [0.42714326, 0.57285674],
       [0.78172966, 0.21827034],
       [0.08377188, 0.91622812],
       [0.32121844, 0.67878156],
       [0.29360424, 0.70639576],
       [0.07963423, 0.92036577],
       [0.82516248, 0.17483752],
       [0.80391179, 0.19608821],
       [0.07172414, 0.92827586],
       [0.02133984, 0.97866016],
       [0.04295117, 0.95704883],
       [0.13742255, 0.86257745],
       [0.8532987 , 0.1467013 ],
       [0.59955155, 0.40044845],
       [0.75734262, 0.24265738],
       [0.09241306, 0.90758694],
       [0.36902961, 0.63097039],
       [0.03071394, 0.96928606],
       [0.78123925, 0.21876075],
       [0.78172966, 0.21827034],
       [0.33303555, 0.66696445],
       [0.33303555, 0.66696445],
       [0.16828617, 0.83171383],
       [0.76972297, 0.23027703],
       [0.62071674, 0.37928326],
       [0.87776282, 0.12223718],
       [0.09807961, 0.90192039],
       [0.78172966, 0.21827034],
       [0.

In [54]:
predicted_proba[:,1]

array([0.32655377, 0.40273561, 0.57285674, 0.21827034, 0.91622812,
       0.67878156, 0.70639576, 0.92036577, 0.17483752, 0.19608821,
       0.92827586, 0.97866016, 0.95704883, 0.86257745, 0.1467013 ,
       0.40044845, 0.24265738, 0.90758694, 0.63097039, 0.96928606,
       0.21876075, 0.21827034, 0.66696445, 0.66696445, 0.83171383,
       0.23027703, 0.37928326, 0.12223718, 0.90192039, 0.21827034,
       0.90657377, 0.64799089, 0.7080988 , 0.93693759, 0.21827034,
       0.94058145, 0.18501571, 0.15732155, 0.37866153, 0.4892728 ,
       0.20672677, 0.47794163, 0.206732  , 0.4892728 , 0.82690782,
       0.09174127, 0.70987562, 0.24324978, 0.21603375, 0.19564092,
       0.66164995, 0.417812  , 0.67878156, 0.29422317, 0.83615224,
       0.33911957, 0.89534415, 0.23180134, 0.43644443, 0.45348247,
       0.71263722, 0.66355629, 0.24483854, 0.19609324, 0.12986915,
       0.2187553 , 0.15295044, 0.1308051 , 0.83938092, 0.89214539,
       0.18501571, 0.3503766 , 0.91578927, 0.36322626, 0.55806

### Save the model

In [55]:
 import pickle

In [56]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [57]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)